[tool.poetry]
name = "ether-batch"
version = "0.1.0"
description = "에테르 배치"
authors = ["이재우 <jwleeitn@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
fastapi = "^0.112.2"
poetry = "^1.8.3"
uvicorn = {extras = ["standard"], version = "^0.30.6"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
